server:
  port: 7003

eureka:
  instance:
    hostname: eureka7003.com               # eureka 服务端实例名称
  client:
    register-with-eureka: false       # false 表示不向注册中心注册自己
    fetch-registry: false             # false 表示自己就是注册中心，职责就是维护服务实例，并不需要去检索服务
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/  #集群版 将当前的 Eureka Server 注册到 7001 和 7003 上，形成一组互相注册的 Eureka Server 集群
